//! Declaration files captured from the app's last successful build.
//!
//! The deploy pipeline calls [`capture`] with the (still present) build
//! worktree, in a task detached from the deploy itself (`host::deploy`): the
//! app is already serving when the walk runs, and the worktree is dropped only
//! once the capture has read it. It reads every
//! `*.d.ts` / `*.d.mts` / `*.d.cts` plus each package's `package.json` (the TS
//! resolver needs it for `types`/`typings`/`exports`/`typesVersions`) under
//! `node_modules/`. `source.types` serves the capture to the browser editor's
//! language service.
//!
//! Storage is local per app: `RUNNER_WORK_DIR/types/<slug>.json.zst` (zstd,
//! the codec state snapshots already use), written temp+rename. It is
//! regenerated by the next successful deploy, so it is deliberately **not**
//! replicated anywhere — losing it just means the editor starts without
//! declarations, and the capture is deleted with the app and moved on rename.
//!
//! Security: `node_modules` is tenant-written and the runner reads it as root,
//! so the walk never leaves the worktree. A symlink is followed only when its
//! canonical target stays inside the worktree (pnpm's `.pnpm/...` links and
//! npm workspace links qualify), directories are deduped by canonical path so
//! link loops terminate, only regular files are read, and every read is
//! bounded by the per-file and total caps below.
use std::collections::HashSet;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context};
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::config::Config;
use crate::host::exec;
use crate::host::source::SourceFile;

/// Caps on one capture: total files, per-file size and whole-payload size.
/// The per-file cap admits the large single-file declarations real packages
/// ship (`@cloudflare/workers-types/index.d.ts` is ~620 KB).
pub const MAX_TYPES_FILES: usize = 20_000;
pub const MAX_TYPES_FILE: u64 = 4 * 1024 * 1024;
pub const MAX_TYPES_TOTAL: u64 = 48 * 1024 * 1024;
/// A `package.json` larger than this is not a usable manifest.
const MAX_MANIFEST: u64 = 64 * 1024;
/// Directory entries examined before the walk gives up, so a tenant cannot
/// make a deploy traverse a pathological tree.
const MAX_WALK_ENTRIES: usize = 200_000;

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct SourceTypes {
    /// The deploy sha the capture came from; `None` when none was captured.
    pub sha: Option<String>,
    pub files: Vec<SourceFile>,
    pub truncated: bool,
}

impl SourceTypes {
    fn empty() -> Self {
        Self {
            sha: None,
            files: Vec::new(),
            truncated: false,
        }
    }
}

pub fn store_path(cfg: &Config, slug: &str) -> PathBuf {
    exec::work_root(cfg)
        .join("types")
        .join(format!("{slug}.json.zst"))
}

/// Capture declarations from `<worktree>/node_modules` into `store` and return
/// the number of files captured. `store` is [`store_path`]; a caller that
/// hands the work off (the deploy spawns this) computes it up front. Callers
/// must treat a failure as non-fatal: the previous capture stays until the
/// next good deploy.
pub async fn capture(store: &Path, worktree: &Path, sha: &str) -> anyhow::Result<usize> {
    let worktree = worktree
        .canonicalize()
        .with_context(|| format!("canonicalize {}", worktree.display()))?;
    let node_modules = worktree.join("node_modules");
    // A missing (or escaping) `node_modules` captures the empty set: a stale
    // capture from an older sha must not be served for this one.
    let Some(root) = contained_dir(&node_modules, &worktree).await else {
        write(
            store,
            &SourceTypes {
                sha: Some(sha.to_string()),
                ..SourceTypes::empty()
            },
        )
        .await?;
        return Ok(0);
    };
    let tree = worktree.clone();
    let (files, truncated) = tokio::task::spawn_blocking(move || walk(&root, &tree)).await?;
    let count = files.len();
    write(
        store,
        &SourceTypes {
            sha: Some(sha.to_string()),
            files,
            truncated,
        },
    )
    .await?;
    Ok(count)
}

/// The canonical directory `path` points at, if it exists and stays inside
/// `worktree`. Anything else (missing, a link out of the tree) is `None`.
async fn contained_dir(path: &Path, worktree: &Path) -> Option<PathBuf> {
    let canon = tokio::fs::canonicalize(path).await.ok()?;
    canon.starts_with(worktree).then_some(canon)
}

/// Breadth-first walk of `root`, reading the declaration files that fit the
/// caps. Only regular files whose canonical target stays inside `worktree` are
/// read. Directories and files are deduped by canonical path, so a symlink
/// loop terminates and one real file lands under its shallowest logical path
/// (pnpm: `node_modules/dep/…`, not `.pnpm/dep@1/…`). The result is sorted by
/// logical path, so it is deterministic for a given tree.
fn walk(root: &Path, worktree: &Path) -> (Vec<SourceFile>, bool) {
    let mut files: Vec<SourceFile> = Vec::new();
    let mut seen: HashSet<PathBuf> = HashSet::new();
    let mut visited: HashSet<PathBuf> = HashSet::from([root.to_path_buf()]);
    // Logical paths are rooted at `node_modules/`, where the browser's
    // language service resolves bare imports and `types` directives.
    let mut queue =
        std::collections::VecDeque::from([(root.to_path_buf(), PathBuf::from("node_modules"))]);
    let mut total: u64 = 0;
    let mut examined = 0usize;
    let mut truncated = false;
    'walk: while let Some((dir, logical)) = queue.pop_front() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        let mut entries: Vec<_> = entries.filter_map(Result::ok).collect();
        entries.sort_by_key(std::fs::DirEntry::file_name);
        for entry in entries {
            examined += 1;
            if examined > MAX_WALK_ENTRIES || files.len() >= MAX_TYPES_FILES {
                truncated = true;
                break 'walk;
            }
            let name = entry.file_name();
            let Some(name) = name.to_str() else {
                continue;
            };
            let path = dir.join(name);
            let logical = logical.join(name);
            let Ok(meta) = std::fs::symlink_metadata(&path) else {
                continue;
            };
            let resolved = if meta.file_type().is_symlink() {
                // Tenant-written: follow only targets that stay in the worktree.
                match std::fs::canonicalize(&path) {
                    Ok(target) if target.starts_with(worktree) => target,
                    _ => continue,
                }
            } else {
                path
            };
            let Ok(meta) = std::fs::metadata(&resolved) else {
                continue;
            };
            if meta.is_dir() {
                if visited.insert(resolved.clone()) {
                    queue.push_back((resolved, logical));
                }
                continue;
            }
            if !meta.is_file() {
                continue;
            }
            let cap = if name == "package.json" {
                MAX_MANIFEST
            } else if is_declaration(name) {
                MAX_TYPES_FILE
            } else {
                continue;
            };
            // Dedupe by the real file: a linked package is one source, under
            // the logical path it was reached by first.
            if !seen.insert(resolved.clone()) {
                continue;
            }
            if meta.len() > cap {
                continue;
            }
            let Ok(bytes) = std::fs::read(&resolved) else {
                continue;
            };
            if bytes.len() as u64 > cap || total + bytes.len() as u64 > MAX_TYPES_TOTAL {
                truncated = true;
                break 'walk;
            }
            if bytes.contains(&0) {
                continue;
            }
            let Ok(text) = String::from_utf8(bytes) else {
                continue;
            };
            total += text.len() as u64;
            files.push(SourceFile {
                path: logical.to_string_lossy().into_owned(),
                text,
            });
        }
    }
    files.sort_by(|a, b| a.path.cmp(&b.path));
    (files, truncated)
}

fn is_declaration(name: &str) -> bool {
    name.ends_with(".d.ts") || name.ends_with(".d.mts") || name.ends_with(".d.cts")
}

/// Read the stored capture; nothing captured yet is the empty payload (not an
/// error), so the editor works before the first successful deploy.
pub async fn read(cfg: &Config, slug: &str) -> anyhow::Result<SourceTypes> {
    let path = store_path(cfg, slug);
    let packed = match tokio::fs::read(&path).await {
        Ok(packed) => packed,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(SourceTypes::empty()),
        Err(e) => return Err(e).with_context(|| format!("read {}", path.display())),
    };
    let raw = zstd::decode_all(&packed[..]).with_context(|| format!("decompress {}", path.display()))?;
    serde_json::from_slice(&raw).with_context(|| format!("decode {}", path.display()))
}

/// Delete the capture with the app; a missing file is fine.
pub async fn remove(cfg: &Config, slug: &str) -> anyhow::Result<()> {
    let path = store_path(cfg, slug);
    match tokio::fs::remove_file(&path).await {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e).with_context(|| format!("remove {}", path.display())),
    }
}

/// Temp file + rename: a crash mid-write must not leave a partial capture that
/// `read` fails to decode.
async fn write(path: &Path, types: &SourceTypes) -> anyhow::Result<()> {
    let Some(dir) = path.parent() else {
        bail!("types store path has no parent");
    };
    tokio::fs::create_dir_all(dir)
        .await
        .with_context(|| format!("create {}", dir.display()))?;
    let raw = serde_json::to_vec(types).context("encode types")?;
    let packed = zstd::encode_all(&raw[..], 3).context("compress types")?;
    let tmp = dir.join(format!(".{}.tmp", crate::models::new_id()));
    tokio::fs::write(&tmp, &packed)
        .await
        .with_context(|| format!("write {}", tmp.display()))?;
    if let Err(e) = tokio::fs::rename(&tmp, path).await {
        let _ = tokio::fs::remove_file(&tmp).await;
        return Err(e).with_context(|| format!("rename into {}", path.display()));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    //! The walk is the security boundary (root reads a tenant-written tree),
    //! so these drive it directly: escaping links, loops, pnpm-style in-tree
    //! links and the caps. The store roundtrip goes through `capture`/`read`.
    use super::*;

    fn tmp(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("noite-types-{tag}-{}", crate::models::new_id()));
        std::fs::create_dir_all(&dir).expect("temp dir");
        dir.canonicalize().expect("canonical temp dir")
    }

    fn write(path: &Path, text: &str) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("parent");
        }
        std::fs::write(path, text).expect("write");
    }

    fn paths(files: &[SourceFile]) -> Vec<&str> {
        files.iter().map(|f| f.path.as_str()).collect()
    }

    #[test]
    fn walk_collects_declarations_and_manifests_only() {
        let root = tmp("collect");
        let nm = root.join("node_modules");
        write(&nm.join("dep/index.d.ts"), "export const a: number;\n");
        write(&nm.join("dep/index.js"), "module.exports = {};\n");
        write(&nm.join("dep/package.json"), "{\"name\":\"dep\"}\n");
        write(&nm.join("dep/esm/index.d.mts"), "export {};\n");
        write(&nm.join("dep/cjs/index.d.cts"), "export {};\n");
        write(&nm.join("dep/readme.md"), "# dep\n");
        write(&nm.join("dep/src/source.ts"), "export {};\n");

        let (files, truncated) = walk(&nm, &root);
        assert!(!truncated);
        assert_eq!(
            paths(&files),
            [
                "node_modules/dep/cjs/index.d.cts",
                "node_modules/dep/esm/index.d.mts",
                "node_modules/dep/index.d.ts",
                "node_modules/dep/package.json",
            ]
        );
        assert_eq!(files[2].text, "export const a: number;\n");
        std::fs::remove_dir_all(&root).ok();
    }

    #[cfg(unix)]
    #[test]
    fn walk_refuses_links_outside_the_worktree() {
        let dir = tmp("escape");
        let nm = dir.join("node_modules");
        write(&nm.join("ok.d.ts"), "export {};\n");
        // A file link to a platform file, and a directory link to the root.
        std::os::unix::fs::symlink("/etc/passwd", nm.join("evil.d.ts")).expect("file link");
        std::os::unix::fs::symlink("/", nm.join("root")).expect("dir link");
        // A broken link is skipped too.
        std::os::unix::fs::symlink(dir.join("gone"), nm.join("broken.d.ts")).expect("broken link");

        let (files, truncated) = walk(&nm, &dir);
        assert!(!truncated);
        assert_eq!(paths(&files), ["node_modules/ok.d.ts"]);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[cfg(unix)]
    #[test]
    fn walk_survives_a_symlink_loop() {
        let dir = tmp("loop");
        let nm = dir.join("node_modules");
        write(&nm.join("dep/index.d.ts"), "export {};\n");
        // dep/self -> node_modules (an ancestor) and self/self -> itself.
        std::os::unix::fs::symlink("..", nm.join("dep/self")).expect("ancestor link");
        std::os::unix::fs::symlink(".", nm.join("dep/loop")).expect("self link");

        let (files, truncated) = walk(&nm, &dir);
        assert!(!truncated);
        assert_eq!(paths(&files), ["node_modules/dep/index.d.ts"]);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[cfg(unix)]
    #[test]
    fn walk_follows_in_tree_links_to_their_shallowest_path() {
        let dir = tmp("pnpm");
        let nm = dir.join("node_modules");
        let store = nm.join(".pnpm/dep@1.0.0/node_modules/dep");
        write(&store.join("index.d.ts"), "export {};\n");
        write(&store.join("package.json"), "{\"name\":\"dep\"}\n");
        // pnpm's top-level alias, plus a workspace-style link into the repo.
        std::os::unix::fs::symlink(".pnpm/dep@1.0.0/node_modules/dep", nm.join("dep"))
            .expect("pnpm link");
        write(&dir.join("packages/lib/index.d.ts"), "export {};\n");
        std::fs::create_dir_all(nm.join("@w")).expect("scope dir");
        std::os::unix::fs::symlink("../../packages/lib", nm.join("@w/lib")).expect("workspace link");

        let (files, truncated) = walk(&nm, &dir);
        assert!(!truncated);
        // One entry per real file, under the link-visible path — the deep
        // `.pnpm` copy is deduped away.
        assert_eq!(
            paths(&files),
            [
                "node_modules/@w/lib/index.d.ts",
                "node_modules/dep/index.d.ts",
                "node_modules/dep/package.json"
            ]
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn walk_caps_the_file_count() {
        let root = tmp("count");
        let nm = root.join("node_modules");
        std::fs::create_dir_all(&nm).expect("nm");
        for i in 0..(MAX_TYPES_FILES + 5) {
            write(&nm.join(format!("f{i:05}.d.ts")), "export {};\n");
        }
        let (files, truncated) = walk(&nm, &root);
        assert!(truncated);
        assert_eq!(files.len(), MAX_TYPES_FILES);
        assert!(files.windows(2).all(|w| w[0].path < w[1].path));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn walk_caps_per_file_and_total_bytes() {
        let root = tmp("bytes");
        let nm = root.join("node_modules");
        write(
            &nm.join("dep/package.json"),
            &"x".repeat(MAX_MANIFEST as usize + 1),
        );
        write(
            &nm.join("dep/big.d.ts"),
            &"x".repeat(MAX_TYPES_FILE as usize + 1),
        );
        // 13 files at the per-file cap (52 MiB): the total cap stops the walk
        // before the 48 MiB budget is exceeded.
        let chunk = "y".repeat(MAX_TYPES_FILE as usize);
        for i in 0..13 {
            write(&nm.join(format!("bulk/f{i:03}.d.ts")), &chunk);
        }
        let (files, truncated) = walk(&nm, &root);
        assert!(truncated, "total budget must truncate");
        let total: usize = files.iter().map(|f| f.text.len()).sum();
        assert!(total <= MAX_TYPES_TOTAL as usize, "total {total}");
        // The oversized file and manifest were skipped, not counted.
        assert!(!paths(&files).contains(&"node_modules/dep/big.d.ts"));
        assert!(!paths(&files).contains(&"node_modules/dep/package.json"));
        std::fs::remove_dir_all(&root).ok();
    }

    fn test_cfg(dir: &Path) -> Config {
        let mut cfg = crate::config::config_for_tests();
        cfg.work_dir = dir.to_string_lossy().into_owned();
        cfg
    }

    #[tokio::test]
    async fn capture_roundtrips_through_the_store_and_is_deleted() {
        let dir = tmp("store");
        let cfg = test_cfg(&dir);
        let worktree = dir.join("build");
        write(&worktree.join("node_modules/dep/index.d.ts"), "export {};\n");
        write(&worktree.join("node_modules/dep/package.json"), "{\"name\":\"dep\"}\n");

        assert_eq!(
            capture(&store_path(&cfg, "app-a"), &worktree, "abc123")
                .await
                .expect("capture"),
            2
        );
        let stored = read(&cfg, "app-a").await.expect("read");
        assert_eq!(stored.sha.as_deref(), Some("abc123"));
        assert_eq!(
            paths(&stored.files),
            ["node_modules/dep/index.d.ts", "node_modules/dep/package.json"]
        );
        assert!(!stored.truncated);
        assert!(store_path(&cfg, "app-a").exists());

        // A deploy with nothing to capture overwrites the old sha instead of
        // serving a stale capture.
        let bare_worktree = dir.join("empty");
        std::fs::create_dir_all(&bare_worktree).expect("worktree");
        assert_eq!(
            capture(&store_path(&cfg, "app-a"), &bare_worktree, "def456")
                .await
                .expect("capture"),
            0
        );
        let stored = read(&cfg, "app-a").await.expect("read");
        assert_eq!(stored.sha.as_deref(), Some("def456"));
        assert!(stored.files.is_empty());

        remove(&cfg, "app-a").await.expect("remove");
        let missing = read(&cfg, "app-a").await.expect("read after remove");
        assert!(missing.sha.is_none() && missing.files.is_empty());
        remove(&cfg, "app-a").await.expect("remove is idempotent");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[tokio::test]
    async fn capture_never_fails_on_a_missing_worktree() {
        let dir = tmp("missing");
        let cfg = test_cfg(&dir);
        let err = capture(&store_path(&cfg, "app-b"), &dir.join("nope"), "abc").await;
        assert!(err.is_err(), "a missing worktree is the caller's to log");
        std::fs::remove_dir_all(&dir).ok();
    }
}
