// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `actor` every commit-making RPC takes (camelCase JSON): the session
 * user the commit is attributed to. The UI fills it from `sessionUser()`;
 * creation stores it on the app row, so it serializes too.
 */
export type Actor = { userId: string, name: string, };
