// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type App = { id: string, slug: string, name: string, userId: string, status: string, subdomain: string, gitPrefix: string, fleetBucket: string, listenPort: number | null, internalPort: number | null, lastDeploySha: string | null, lastError: string | null, desiredState: string, createdAt: string, updatedAt: string, 
/**
 * Set while the app is asleep (scale to zero); NULL when awake.
 */
asleepSince: string | null, 
/**
 * Last wake (request-driven, manual start or deploy): the idle clock
 * never runs from before it.
 */
wokeAt: string | null, 
/**
 * Whether the row carries a stored import source — the UI's Retry gate.
 * Derived in SQL (`import_source IS NOT NULL`), never a column.
 */
imported: boolean, };
