// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppDeviceStat = { appId: string, bucketTs: string, browser: string, os: string, requests: number, };
