// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppEvent = { id: string, appId: string, channel: string, event: string, description: string, icon: string, tags: string, userId: string, ts: string, };
