// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInsight = { appId: string, title: string, value: string, num: number | null, icon: string, updatedAt: string, };
