// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppPathStat = { appId: string, bucketTs: string, path: string, requests: number, };
