// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated span row served to the dashboard (spec T3.2). Same JSON shape
 * as the old DuckDB-backed `SpanStat` (`qwaitMs`), now read from the
 * ingested `app_span_stat` ring instead of scanning Parquet per viewer.
 */
export type AppSpanStat = { name: string, kind: number, n: number, ms: number, err: number, qwaitMs: number, };
