// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlobResponse = { sha: string, path: string, size: number, truncated: boolean, binary: boolean, text: string, };
