// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type D1Column = { name: string, 
/**
 * Declared type; "" when the DDL has none.
 */
type: string, notNull: boolean, 
/**
 * DDL default expression text; null when none.
 */
defaultValue: string | null, 
/**
 * 0 = not part of the PK, else 1-based position.
 */
pk: number, };
