// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type D1DeleteRowsBody = { table: string, keys: Array<{ [key in string]: string | null }>, };
