// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { D1FilterOp } from "./D1FilterOp";

export type D1Filter = { column: string, op: D1FilterOp, 
/**
 * Ignored for is_null/not_null; `like` takes the user's pattern with `%`
 * wildcards as typed.
 */
value: string, };
