// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type D1FilterOp = "eq" | "neq" | "lt" | "lte" | "gt" | "gte" | "like" | "is_null" | "not_null";
