// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type D1Rows = { table: string, 
/**
 * Column order of `rows`.
 */
columns: Array<string>, rows: Array<Array<string | null>>, 
/**
 * COUNT(*) under the same filters/search.
 */
total: number, page: number, pageSize: number, };
