// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { D1Column } from "./D1Column";
import type { D1ForeignKey } from "./D1ForeignKey";
import type { D1Index } from "./D1Index";

export type D1TableSchemaRaw = { table: string, columns: Array<D1Column>, foreignKeys: Array<D1ForeignKey>, indexes: Array<D1Index>, sql: string | null, };
