// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { D1TableInfo } from "./D1TableInfo";

export type D1Tables = { databaseId: string, tables: Array<D1TableInfo>, };
