// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { D1WriteOp } from "./D1WriteOp";

export type D1WriteBody = { op: D1WriteOp, table: string, 
/**
 * update/delete row identity.
 */
key?: { [key in string]: string | null }, 
/**
 * insert/update; null = SQL NULL, "" = empty string.
 */
values: { [key in string]: string | null }, };
