// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Deploy = { id: string, appId: string, sha: string | null, status: string, log: string, createdAt: string, updatedAt: string, };
