// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffResponse = { sha: string, parent: string | null, patch: string, truncated: boolean, };
