// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoInstance } from "./DoInstance";

export type DoPreview = { appId: string, appSlug: string, className: string, instances: Array<DoInstance>, };
