// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One grouped error (host/errors.rs): every occurrence with the same
 * fingerprint. `status` is `open`, `resolved` or `ignored`; `regressed`
 * marks a resolved issue that fired again.
 */
export type ErrorIssue = { fingerprint: string, kind: string, message: string, culprit: string, handler: string, source: string, count: number, firstSeenUs: number, lastSeenUs: number, firstSha: string | null, lastSha: string | null, status: string, regressed: boolean, statusAtUs: number | null, };
