// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One issue plus its 24-hour series (the `hourly` field the RPC inlines).
 */
export type ErrorIssueView = { hourly: Array<number>, fingerprint: string, kind: string, message: string, culprit: string, handler: string, source: string, count: number, firstSeenUs: number, lastSeenUs: number, firstSha: string | null, lastSha: string | null, status: string, regressed: boolean, statusAtUs: number | null, };
