// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-status issue counts.
 */
export type ErrorCounts = { open: number, resolved: number, ignored: number, };
