// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCounts } from "./ErrorCounts";
import type { ErrorIssueView } from "./ErrorIssueView";

/**
 * The `errors.list` result and the errors stream frame.
 */
export type ErrorIssueList = { issues: Array<ErrorIssueView>, counts: ErrorCounts, };
