// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorEventView } from "./ErrorEventView";
import type { ErrorIssueView } from "./ErrorIssueView";

/**
 * The `errors.get` result: the issue plus its recent events.
 */
export type ErrorIssueDetail = { issue: ErrorIssueView, events: Array<ErrorEventView>, };
