// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from "./Frame";

/**
 * One stored occurrence with its frames/logs parsed from their JSON text.
 */
export type ErrorEventView = { tsUs: number, traceId: string, source: string, handler: string, cell: string, kind: string, message: string, context: string, frames: Array<Frame>, logs: Array<string>, method: string, path: string, httpStatus: number, browser: string, os: string, sha: string, };
