// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One branch tip, with its distance from `main`.
 */
export type GitBranch = { name: string, sha: string, committedAt: number, authorName: string, subject: string, ahead: number, behind: number, };
