// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitCommitSummary } from "./GitCommitSummary";
import type { GitFileStat } from "./GitFileStat";

/**
 * `base..head`: the commits only on `head`, the three-dot file list and
 * patch, and whether a squash merge would land cleanly.
 */
export type GitCompare = { base: string, head: string, baseSha: string, headSha: string, mergeBase: string | null, ahead: number, behind: number, commits: Array<GitCommitSummary>, files: Array<GitFileStat>, patch: string, truncated: boolean, mergeable: boolean, conflicts: Array<string>, };
