// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit's metadata, as the UI lists it.
 */
export type GitCommitSummary = { sha: string, parents: Array<string>, authorName: string, authorEmail: string, authoredAt: number, committerName: string, committedAt: number, subject: string, };
