// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitCommitSummary } from "./GitCommitSummary";
import type { GitFileStat } from "./GitFileStat";

/**
 * One commit: metadata, body, files and the patch against its first parent
 * (or the empty tree for a root commit).
 */
export type GitCommitDetail = { commit: GitCommitSummary, body: string, files: Array<GitFileStat>, patch: string, truncated: boolean, };
