// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatus } from "./GitFileStatus";

/**
 * One file in a diff. `additions`/`deletions` are null for a binary file.
 */
export type GitFileStat = { path: string, oldPath: string | null, additions: number | null, deletions: number | null, status: GitFileStatus, };
