// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one file changed between two trees.
 */
export type GitFileStatus = "added" | "modified" | "deleted" | "renamed";
