// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitCommitSummary } from "./GitCommitSummary";

/**
 * One page of history. `nextSkip` is null on the last page.
 */
export type GitLog = { commits: Array<GitCommitSummary>, nextSkip: number | null, };
