// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitBranch } from "./GitBranch";

/**
 * Every branch plus what the Source page needs to pick a default: the
 * deployed sha when there is one.
 */
export type GitRefs = { defaultBranch: string, deployedSha: string | null, branches: Array<GitBranch>, };
