// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clone/browse coordinates. `url` is the stock remote; `s3Remote` is the
 * internal layout (debug).
 */
export type GitRemote = { url: string, username: string, s3Remote: string, endpoint: string, bucket: string, prefix: string, };
