// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The platform defaults an app's limits fall back to.
 */
export type LimitDefaults = { clientRpm: number, appRpm: number, };
