// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitDefaults } from "./LimitDefaults";

/**
 * An app's edge limits as the settings panel shows them: its own values
 * (null = default) beside the platform defaults they fall back to.
 * `perClient` is false behind a proxy the edge does not trust, where
 * per-client limits cannot apply (`Config::edge_sees_clients`).
 */
export type LimitsView = { clientRpm: number | null, appRpm: number | null, perClient: boolean, defaults: LimitDefaults, };
