// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A comment. A line comment carries its anchor (`path`, `line`, `side` and
 * the `commit_sha` it was written against); `outdated` says that anchor no
 * longer matches the current diff.
 */
export type PrComment = { id: string, authorId: string, body: string, path: string | null, line: number | null, side: string | null, commitSha: string | null, createdAt: string, editedAt: string | null, outdated: boolean, };
