// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitCompare } from "./GitCompare";
import type { PrComment } from "./PrComment";
import type { PrReview } from "./PrReview";
import type { PrSummary } from "./PrSummary";

/**
 * `mergeState` values the merge box renders.
 */
export type PrDetail = { pullRequest: PrSummary, comments: Array<PrComment>, reviews: Array<PrReview>, 
/**
 * The live `base..head` compare; `None` when the head branch is gone.
 */
compare: GitCompare | null, approvals: number, requiredApprovals: number, requirePr: boolean, mergeState: string, };
