// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrCounts } from "./PrCounts";
import type { PrSummary } from "./PrSummary";

export type PrList = { pullRequests: Array<PrSummary>, counts: PrCounts, };
