// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrReview = { id: string, reviewerId: string, state: string, commitSha: string, createdAt: string, dismissedAt: string | null, };
