// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A PR as the list and detail pages show it.
 */
export type PrSummary = { number: number, title: string, body: string, authorId: string, base: string, head: string, state: string, headSha: string, mergeSha: string | null, mergedBy: string | null, createdAt: string, updatedAt: string, closedAt: string | null, mergedAt: string | null, commentCount: number, };
