// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type R2File = { key: string, size: number, truncated: boolean, contentType: string | null, 
/**
 * UTF-8 body (up to the preview cap); None for binary objects.
 */
text: string | null, };
