// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type R2Folder = { name: string, 
/**
 * Key prefix of the folder, including its trailing `/`.
 */
prefix: string, };
