// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type R2Object = { key: string, name: string, size: number, lastModified: string, contentType: string | null, etag: string | null, };
