// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { R2Folder } from "./R2Folder";
import type { R2Object } from "./R2Object";

export type R2Preview = { appId: string, appSlug: string, bucket: string, 
/**
 * The folder the page lists (decoded key prefix, `""` at the root).
 */
prefix: string, folders: Array<R2Folder>, objects: Array<R2Object>, 
/**
 * Continuation token for the next page, `null` on the last one.
 */
nextCursor: string | null, };
