// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One browser-edited file: validated path + text content.
 */
export type SourceCommitFile = { path: string, content: string, };
