// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceCommitFile } from "./SourceCommitFile";

/**
 * Browser-edit commit body: validated paths + text contents, a short
 * message, and the collaborator email used as the git author.
 */
export type SourceCommitBody = { files: Array<SourceCommitFile>, message: string, author: string, };
