// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One text source crossing the wire: the same shape `source.bundle` and
 * `source.types` both use, so the editor loads either into one map.
 */
export type SourceFile = { path: string, text: string, };
