// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceFile } from "./SourceFile";

export type SourceBundle = { sha: string, files: Array<SourceFile>, truncated: boolean, };
