// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Actor } from "./Actor";
import type { SourceCommitFile } from "./SourceCommitFile";

/**
 * Browser-edit commit body: validated paths + text contents, a short
 * message, the session user the commit is attributed to, and — when the UI
 * commits to something other than `main` — the target branch, plus the ref a
 * new branch starts from.
 */
export type SourceCommitBody = { actor: Actor, files: Array<SourceCommitFile>, message: string, branch?: string, fromSha?: string, 
/**
 * The caller's app role; `require_pr` blocks a non-admin commit to
 * `main` (`None` counts as a non-admin).
 */
role?: string, };
