// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceFile } from "./SourceFile";

export type SourceTypes = { 
/**
 * The deploy sha the capture came from; `None` when none was captured.
 */
sha: string | null, files: Array<SourceFile>, truncated: boolean, };
