// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageItem = { appId: string, appSlug: string, appName: string, kind: string, id: string, name: string, };
