// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelemetryEvent } from "./TelemetryEvent";

/**
 * `telemetry.get` / `GET /v1/admin/telemetry` and the `set` reply. `enabled`
 * is the effective state (stored preference AND not locked); `setting` is
 * what the operator stored.
 */
export type TelemetryStatus = { enabled: boolean, setting: boolean, locked: boolean, lockReason: string | null, lastSentAt: string | null, installId: string, 
/**
 * The exact body a send right now would POST (`api_key` included).
 */
preview: TelemetryEvent, };
