// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The heartbeat facts. Property names are the contract's, exactly.
 */
export type TelemetryProperties = { version: string, celld_version: string, arch: string, tenancy: string, storage: string, apps: number, apps_running: number, apps_sleeping: number, deploys_24h: number, deploys_failed_24h: number, 
/**
 * Bucket string (`"1"`, `"2-5"`, `"6-20"`, `"21+"`), never the count;
 * `"unknown"` when the control worker could not be reached.
 */
users: string, install_age_days: number, uptime_hours: number, 
/**
 * PostHog: never geolocate the sender's IP.
 */
$geoip_disable: boolean, 
/**
 * PostHog: never build a person profile for the install id.
 */
$process_person_profile: boolean, };
