// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelemetryProperties } from "./TelemetryProperties";

/**
 * The exact PostHog capture body. `api_key`/`distinct_id` are PostHog's own
 * snake_case body keys, and `properties` carries the heartbeat facts plus the
 * two `$`-prefixed PostHog controls. Serialized as-is into the request.
 */
export type TelemetryEvent = { api_key: string, event: string, distinct_id: string, timestamp: string, properties: TelemetryProperties, };
