// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeEntry } from "./TreeEntry";

export type TreeResponse = { sha: string, files: Array<TreeEntry>, truncated: boolean, };
